export const projectOrder = [
  "amg-black-series",
  "luxe-beauty",
  "hygenika",
  "amdrix",
  "virtual-accountant",
  "rolex-gmt-master-ii",
  "cognitive-corporate-finance",
];

export const projects = {
  "amg-black-series": {
    number: "01",
    title: "AMG GT Black Series",
    shortTitle: "AMG Black Series",
    type: "Personal concept / Automotive / Three.js",
    subtitle: "An interactive Three.js showcase where visitors ignite the AMG GT Black Series, activate its lighting and guide the camera through front, profile, rear and departure scenes.",
    description: "An unofficial real-time 3D AMG GT Black Series experience built with Three.js and WebGL, featuring an ignition interaction, animated studio lighting, scroll-controlled camera movement and a responsive cinematic interface.",
    image: "assets/projects/amg-black-series-card-square.png",
    alt: "AMG GT Black Series interactive website preview",
    liveUrl: "https://ariankapllanaj.github.io/AMG-GT-Black-Series-Experience/",
    accent: "#58f08b", accentSecondary: "#163f29",
    year: "2026", client: "Personal concept", market: "Global",
    role: "Creative direction & development", status: "Live",
    overviewTitle: "Turning an automotive showcase into a digital event.",
    overviewBody: "The concept replaces a conventional automotive landing page with a staged digital launch. Visitors begin in a nearly dark studio, start the car themselves and then control a sequence of lighting changes, camera angles and vehicle movement through scrolling. A real-time GLB model, custom WebGL lighting and responsive scene framing keep the AMG GT Black Series at the centre of the experience.",
    challengeTitle: "The challenge",
    challengeBody: "A detailed 3D model can quickly become heavy and difficult to control. The interface needed to keep the car as the hero while preserving readable typography and smooth motion across screens.",
    solutionTitle: "The experience",
    solutionBody: "The site opens in darkness and invites the visitor to start the car. Light, camera movement and scroll progress then reveal the vehicle from multiple angles before the final AMG statement lands.",
    features: [
      ["01", "Ignition sequence", "A deliberate start interaction activates the lights and unlocks the experience."],
      ["02", "Scroll choreography", "Camera position, lighting and vehicle movement respond to scroll progress."],
      ["03", "Real-time 3D", "Three.js renders the vehicle inside a cinematic studio environment."],
      ["04", "Responsive direction", "Typography and scene framing adapt across desktop, tablet and mobile."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Three.js", "WebGL", "GLB"],
  },

  "luxe-beauty": {
    number: "02", title: "Luxe Beauty Studio", shortTitle: "Luxe Beauty",
    type: "Client website / Beauty / Booking",
    subtitle: "A responsive German-language website for a beauty studio in Brig-Glis, presenting lash, brow, nail and smile services with direct Fresha appointment booking.",
    description: "Website for Luxe Beauty Studio in Brig-Glis, Switzerland, with dedicated service, gallery, about and contact sections, Fresha booking links, a contact form, map and mobile-friendly navigation.",
    image: "assets/projects/luxe-beauty-studio.png", alt: "Luxe Beauty Studio website preview",
    liveUrl: "https://luxebeautystudio.ch", accent: "#d5aa78", accentSecondary: "#4b392e",
    year: "2026", client: "Luxe Beauty Studio", market: "Brig-Glis, Switzerland",
    role: "Web design & development", status: "Live",
    overviewTitle: "A premium experience with a clear business purpose.",
    overviewBody: "The website brings the studio's lash, brow, nail and smile treatments into one coherent premium identity. Soft beige tones, editorial typography and generous spacing create a calm luxury atmosphere, while dedicated service information, a visual gallery, founder introductions, location details and Fresha links guide visitors from first discovery to a confirmed appointment.",
    challengeTitle: "The challenge",
    challengeBody: "The brand offers several services through two specialists. The content had to remain refined while making treatments, location, contact information and booking immediately understandable.",
    solutionTitle: "The approach",
    solutionBody: "A clean hierarchy, subtle reveals and direct calls to action connect the brand story with practical client needs. Fresha booking and contact options stay easy to reach on every device.",
    features: [
      ["01", "Luxury direction", "A restrained palette and elegant typography establish a premium character."],
      ["02", "Service discovery", "Focused service cards explain the offer without unnecessary text."],
      ["03", "Fresha booking", "Appointment actions connect directly to the studio's booking flow."],
      ["04", "Mobile experience", "Navigation, gallery and contact areas are optimised for mobile clients."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Formspree", "Fresha", "Responsive UI"],
  },

  hygenika: {
    number: "03", title: "Hygenika Facility Service", shortTitle: "Hygenika",
    type: "Client website / Facility services / Brand",
    subtitle: "A German-language company website for Hygenika Facility Service GmbH, clearly presenting building maintenance and professional cleaning services across Switzerland.",
    description: "Responsive website for Hygenika Facility Service GmbH with separate service paths for building maintenance and cleaning, high-contrast enquiry buttons, company information and mobile navigation.",
    image: "assets/projects/hygenika.png", alt: "Hygenika facility services website preview",
    liveUrl: "https://hygenika.ch", accent: "#ff2b2b", accentSecondary: "#4b1717",
    year: "2026", client: "Hygenika Facility Service GmbH", market: "Switzerland",
    role: "Web design & development", status: "Live",
    overviewTitle: "Making a service business feel precise and dependable.",
    overviewBody: "The website separates Hygenika's two core offers—building maintenance and professional cleaning—into clear customer journeys. Dark editorial photography, strong white typography and a focused red accent create a recognisable brand, while company information, service explanations and prominent offer requests help Swiss property owners understand the business and make contact quickly.",
    challengeTitle: "The challenge",
    challengeBody: "Facility-service websites often look interchangeable. The task was to build a recognisable brand presence while keeping the path to an offer fast and direct.",
    solutionTitle: "The approach",
    solutionBody: "Large service imagery, concise German copy and high-contrast actions create a clear journey. Responsive navigation keeps the experience practical on mobile devices.",
    features: [
      ["01", "Service clarity", "Building maintenance and cleaning have clear visual pathways."],
      ["02", "Trust-led design", "Dark editorial photography creates a professional tone."],
      ["03", "Direct enquiries", "Prominent offer and contact actions reduce friction."],
      ["04", "Responsive navigation", "Desktop and mobile use tailored navigation behaviour."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Responsive UI", "SEO", "Contact forms"],
  },

  amdrix: {
    number: "04", title: "Amdrix Hauswartung & Reinigung", shortTitle: "Amdrix",
    type: "Client website / Property care / Lead generation",
    subtitle: "A multi-page German-language website for Swiss property maintenance and cleaning, built around immediate service clarity and direct quote, phone and WhatsApp enquiries.",
    description: "Lead-focused website for Amdrix Hauswartung & Reinigung, with dedicated service pages, customer proof, before-and-after interactions and prominent Call, WhatsApp and Request an Offer actions.",
    image: "assets/projects/amdrix.png", alt: "Amdrix property maintenance website preview",
    liveUrl: "https://ariankapllanaj.github.io/amdrix.ch/", accent: "#91cf38", accentSecondary: "#193f35",
    year: "2026", client: "Amdrix Hauswartung & Reinigung", market: "Switzerland",
    role: "Web design & development", status: "Live",
    overviewTitle: "A service website built for immediate understanding.",
    overviewBody: "The first viewport explains who Amdrix is, which property-maintenance and cleaning services it provides, where it operates and how to request a non-binding offer. Dedicated pages give each service enough detail without overloading the homepage, while proof points, before-and-after content and persistent Call, WhatsApp and offer actions support conversion on desktop and mobile.",
    challengeTitle: "The challenge",
    challengeBody: "The company serves different customer groups and offers several services. The content needed to stay concise while providing enough proof and contact options to build confidence.",
    solutionTitle: "The approach",
    solutionBody: "A structured multi-page architecture, strong hero messaging and visible phone, WhatsApp and offer actions give every visitor a direct next step.",
    features: [
      ["01", "Conversion-first hero", "The main message and enquiry actions appear immediately."],
      ["02", "Contact choice", "Call, WhatsApp and offer buttons support different visitors."],
      ["03", "Service architecture", "Dedicated pages add detail without overloading the homepage."],
      ["04", "Proof and motion", "Metrics and comparison interactions reinforce service quality."],
    ],
    stack: ["Vite", "HTML", "CSS", "JavaScript", "Responsive UI", "GitHub Pages"],
  },

  "virtual-accountant": {
    number: "05", title: "Virtual Accountant UK", shortTitle: "Virtual Accountant",
    type: "Business website / Finance / Professional services",
    subtitle: "A business website for UK companies seeking remote bookkeeping, management reporting, payroll, tax preparation and practical financial support.",
    description: "Responsive website for Virtual Accountant UK that explains bookkeeping, reporting, payroll and tax services, highlights secure cloud-first workflows and guides business owners toward booking a meeting.",
    image: "assets/projects/virtual-accountant.png", alt: "Virtual Accountant UK website preview",
    liveUrl: "https://virtual-accountant.uk", accent: "#00b996", accentSecondary: "#103e59",
    year: "2026", client: "Virtual Accountant UK", market: "United Kingdom",
    role: "Web design & development", status: "Live",
    overviewTitle: "Complex financial services, presented with clarity.",
    overviewBody: "The website translates bookkeeping, management reporting, payroll, tax preparation and financial decision support into a clear service journey for modern UK businesses. Deep-blue typography and teal data visuals communicate professionalism, while plain-language explanations, cloud-first and confidentiality signals, client tools and meeting calls to action make remote accounting support feel understandable and dependable.",
    challengeTitle: "The challenge",
    challengeBody: "Financial websites need to communicate competence and security without feeling cold or overly technical. The message also had to work for business owners with different financial knowledge.",
    solutionTitle: "The approach",
    solutionBody: "Plain-language copy, visual service cues and a strong meeting action create a reassuring path from first impression to enquiry.",
    features: [
      ["01", "Clear positioning", "The hero explains the remote accounting offer directly."],
      ["02", "Service mapping", "Bookkeeping, payroll, tax and reporting are organised clearly."],
      ["03", "Trust signals", "Security, flexibility and cloud-first workflows appear early."],
      ["04", "Meeting conversion", "Focused calls to action move visitors toward a conversation."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Responsive UI", "SEO", "Contact workflow"],
  },

  "rolex-gmt-master-ii": {
    number: "06", title: "Rolex GMT-Master II", shortTitle: "Rolex GMT-Master II",
    type: "Unofficial concept / Luxury / Interactive web",
    subtitle: "An unofficial scroll-driven product experience for the two-tone Rolex GMT-Master II, using layered parallax, Three.js scenes and controlled motion to explore its travel function, construction and visual details.",
    description: "Unofficial interactive Rolex GMT-Master II concept built with HTML, CSS, JavaScript and Three.js, combining cinematic transitions, parallax depth and responsive product storytelling in a dark green and gold visual system.",
    image: "assets/projects/rolex-gmt-master2.png", alt: "Rolex GMT-Master II website preview",
    liveUrl: "https://ariankapllanaj.github.io/rolex-gmt-master2-2tone-gold-website/",
    accent: "#d6b35f", accentSecondary: "#263d31",
    year: "2026", client: "Personal concept", market: "Global",
    role: "Creative direction & development", status: "Live",
    overviewTitle: "Luxury storytelling through interaction and restraint.",
    overviewBody: "This personal concept treats the two-tone GMT-Master II as the subject of an interactive luxury campaign rather than a standard product catalogue. Scroll-controlled scenes, layered parallax and Three.js depth guide visitors through the watch's travel identity, construction and precision details, while deep green, black and gold art direction preserves the restrained character expected from a high-end timepiece presentation.",
    challengeTitle: "The challenge",
    challengeBody: "The watch contains many small details, while the experience needed to remain elegant rather than becoming a technical catalogue. Motion had to reveal information without competing with the product.",
    solutionTitle: "The experience",
    solutionBody: "Scroll-led scenes, layered depth and carefully timed typography build a guided narrative around travel, construction and precision.",
    features: [
      ["01", "Cinematic pacing", "Content appears through controlled scroll sequences."],
      ["02", "Luxury art direction", "Deep green, black and gold create a premium system."],
      ["03", "Product storytelling", "Design details join one continuous narrative."],
      ["04", "Responsive motion", "Effects scale down to preserve clarity and performance."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Three.js", "Motion", "Responsive UI"],
  },

  "cognitive-corporate-finance": {
    number: "07", title: "Cognitive Corporate Finance", shortTitle: "CognitiveCF",
    type: "Corporate website / Finance / Advisory",
    subtitle: "A corporate website for an international merchant advisory firm, presenting its technology-enhanced, Big Data-powered approach to capital raising and transaction support.",
    description: "Corporate website for Cognitive Corporate Finance, organizing its services, network, ecosystem, resources, funding proposition, team and contact pathways within a responsive international advisory platform.",
    image: "assets/projects/ccf.png", alt: "Cognitive Corporate Finance website preview",
    liveUrl: "https://www.cognitivecf.com", accent: "#9fb7c6", accentSecondary: "#293138",
    year: "2026", client: "Cognitive Corporate Finance", market: "International",
    role: "Digital presence", status: "Live",
    overviewTitle: "A corporate platform built around a differentiated proposition.",
    overviewBody: "The platform explains how Cognitive Corporate Finance combines merchant-advisory experience, technology and Big Data to support capital raising and transactions. A direct positioning statement leads into structured areas for services, network, ecosystem, resources, funding support, team and contact, helping companies and investors understand both the firm's capabilities and its differentiated international approach.",
    challengeTitle: "The challenge",
    challengeBody: "Corporate finance is complex and trust-sensitive. The proposition needed to feel credible while explaining what makes the firm's approach different from traditional advisory models.",
    solutionTitle: "The approach",
    solutionBody: "A concise positioning statement leads into structured corporate content. Monochrome visuals and straightforward navigation support clarity across the firm's ecosystem.",
    features: [
      ["01", "Distinct positioning", "The technology-enhanced approach leads the experience."],
      ["02", "Corporate clarity", "Services, network, resources and team follow a clear model."],
      ["03", "International tone", "Neutral visual language supports a cross-border audience."],
      ["04", "Responsive access", "Key content and contact pathways work across devices."],
    ],
    stack: ["WordPress", "CSS", "JavaScript", "Responsive UI", "Corporate content", "SEO", "Elementor"],
  },
};
