export const projectOrder = [
  "luxe-beauty",
  "hygenika",
  "amdrix",
  "virtual-accountant",
  "ai-social-media-manager",
  "cognitive-corporate-finance",
  "ccf-apollo-email-tool",
];

export const projects = {
  "luxe-beauty": {
    number: "02", title: "Luxe Beauty Studio", shortTitle: "Luxe Beauty",
    type: "Client website / Beauty / Booking",
    subtitle: "A responsive German-language website for a beauty studio in Brig-Glis, presenting lash, brow, nail and smile services with direct Fresha appointment booking.",
    description: "Website for Luxe Beauty Studio in Brig-Glis, Switzerland, with dedicated service, gallery, about and contact sections, Fresha booking links, a contact form, map and mobile-friendly navigation.",
    image: "assets/projects/luxe-beauty-studio.png", alt: "Luxe Beauty Studio website preview",
    liveUrl: "https://luxebeautystudio.ch", accent: "#d5aa78", accentSecondary: "#4b392e",
    year: "2026", client: "Luxe Beauty Studio", market: "Brig-Glis, Switzerland",
    role: "Web design & development", status: "Live",
    overviewTitle: "A premium experience with a clear business purpose.",
    overviewBody: "The website brings the studio's lash, brow, nail and smile treatments into one coherent premium identity. Soft beige tones, editorial typography and generous spacing create a calm luxury atmosphere, while dedicated service information, a visual gallery, founder introductions, location details and Fresha links guide visitors from first discovery to a confirmed appointment.",
    challengeTitle: "The challenge",
    challengeBody: "The brand offers several services through two specialists. The content had to remain refined while making treatments, location, contact information and booking immediately understandable.",
    solutionTitle: "The approach",
    solutionBody: "A clean hierarchy, subtle reveals and direct calls to action connect the brand story with practical client needs. Fresha booking and contact options stay easy to reach on every device.",
    features: [
      ["01", "Luxury direction", "A restrained palette and elegant typography establish a premium character."],
      ["02", "Service discovery", "Focused service cards explain the offer without unnecessary text."],
      ["03", "Fresha booking", "Appointment actions connect directly to the studio's booking flow."],
      ["04", "Mobile experience", "Navigation, gallery and contact areas are optimised for mobile clients."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Formspree", "Fresha", "Responsive UI"],
  },

  hygenika: {
    number: "03", title: "Hygenika Facility Service", shortTitle: "Hygenika",
    type: "Client website / Facility services / Brand",
    subtitle: "A German-language company website for Hygenika Facility Service GmbH, clearly presenting building maintenance and professional cleaning services across Switzerland.",
    description: "Responsive website for Hygenika Facility Service GmbH with separate service paths for building maintenance and cleaning, high-contrast enquiry buttons, company information and mobile navigation.",
    image: "assets/projects/hygenika.png", alt: "Hygenika facility services website preview",
    liveUrl: "https://hygenika.ch", accent: "#ff2b2b", accentSecondary: "#4b1717",
    year: "2026", client: "Hygenika Facility Service GmbH", market: "Switzerland",
    role: "Web design & development", status: "Live",
    overviewTitle: "Making a service business feel precise and dependable.",
    overviewBody: "The website separates Hygenika's two core offers—building maintenance and professional cleaning—into clear customer journeys. Dark editorial photography, strong white typography and a focused red accent create a recognisable brand, while company information, service explanations and prominent offer requests help Swiss property owners understand the business and make contact quickly.",
    challengeTitle: "The challenge",
    challengeBody: "Facility-service websites often look interchangeable. The task was to build a recognisable brand presence while keeping the path to an offer fast and direct.",
    solutionTitle: "The approach",
    solutionBody: "Large service imagery, concise German copy and high-contrast actions create a clear journey. Responsive navigation keeps the experience practical on mobile devices.",
    features: [
      ["01", "Service clarity", "Building maintenance and cleaning have clear visual pathways."],
      ["02", "Trust-led design", "Dark editorial photography creates a professional tone."],
      ["03", "Direct enquiries", "Prominent offer and contact actions reduce friction."],
      ["04", "Responsive navigation", "Desktop and mobile use tailored navigation behaviour."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Responsive UI", "SEO", "Contact forms"],
  },

  amdrix: {
    number: "04", title: "Amdrix Hauswartung & Reinigung", shortTitle: "Amdrix",
    type: "Client website / Property care / Lead generation",
    subtitle: "A multi-page German-language website for Swiss property maintenance and cleaning, built around immediate service clarity and direct quote, phone and WhatsApp enquiries.",
    description: "Lead-focused website for Amdrix Hauswartung & Reinigung, with dedicated service pages, customer proof, before-and-after interactions and prominent Call, WhatsApp and Request an Offer actions.",
    image: "assets/projects/amdrix.png", alt: "Amdrix property maintenance website preview",
    liveUrl: "https://ariankapllanaj.github.io/amdrix.ch/", accent: "#91cf38", accentSecondary: "#193f35",
    year: "2026", client: "Amdrix Hauswartung & Reinigung", market: "Switzerland",
    role: "Web design & development", status: "Live",
    overviewTitle: "A service website built for immediate understanding.",
    overviewBody: "The first viewport explains who Amdrix is, which property-maintenance and cleaning services it provides, where it operates and how to request a non-binding offer. Dedicated pages give each service enough detail without overloading the homepage, while proof points, before-and-after content and persistent Call, WhatsApp and offer actions support conversion on desktop and mobile.",
    challengeTitle: "The challenge",
    challengeBody: "The company serves different customer groups and offers several services. The content needed to stay concise while providing enough proof and contact options to build confidence.",
    solutionTitle: "The approach",
    solutionBody: "A structured multi-page architecture, strong hero messaging and visible phone, WhatsApp and offer actions give every visitor a direct next step.",
    features: [
      ["01", "Conversion-first hero", "The main message and enquiry actions appear immediately."],
      ["02", "Contact choice", "Call, WhatsApp and offer buttons support different visitors."],
      ["03", "Service architecture", "Dedicated pages add detail without overloading the homepage."],
      ["04", "Proof and motion", "Metrics and comparison interactions reinforce service quality."],
    ],
    stack: ["Vite", "HTML", "CSS", "JavaScript", "Responsive UI", "GitHub Pages"],
  },

  "virtual-accountant": {
    number: "05", title: "Virtual Accountant UK", shortTitle: "Virtual Accountant",
    type: "Business website / Finance / Professional services",
    subtitle: "A business website for UK companies seeking remote bookkeeping, management reporting, payroll, tax preparation and practical financial support.",
    description: "Responsive website for Virtual Accountant UK that explains bookkeeping, reporting, payroll and tax services, highlights secure cloud-first workflows and guides business owners toward booking a meeting.",
    image: "assets/projects/virtual-accountant.png", alt: "Virtual Accountant UK website preview",
    liveUrl: "https://virtual-accountant.uk", accent: "#00b996", accentSecondary: "#103e59",
    year: "2026", client: "Virtual Accountant UK", market: "United Kingdom",
    role: "Web design & development", status: "Live",
    overviewTitle: "Complex financial services, presented with clarity.",
    overviewBody: "The website translates bookkeeping, management reporting, payroll, tax preparation and financial decision support into a clear service journey for modern UK businesses. Deep-blue typography and teal data visuals communicate professionalism, while plain-language explanations, cloud-first and confidentiality signals, client tools and meeting calls to action make remote accounting support feel understandable and dependable.",
    challengeTitle: "The challenge",
    challengeBody: "Financial websites need to communicate competence and security without feeling cold or overly technical. The message also had to work for business owners with different financial knowledge.",
    solutionTitle: "The approach",
    solutionBody: "Plain-language copy, visual service cues and a strong meeting action create a reassuring path from first impression to enquiry.",
    features: [
      ["01", "Clear positioning", "The hero explains the remote accounting offer directly."],
      ["02", "Service mapping", "Bookkeeping, payroll, tax and reporting are organised clearly."],
      ["03", "Trust signals", "Security, flexibility and cloud-first workflows appear early."],
      ["04", "Meeting conversion", "Focused calls to action move visitors toward a conversation."],
    ],
    stack: ["HTML", "CSS", "JavaScript", "Responsive UI", "SEO", "Contact workflow"],
  },

  "ai-social-media-manager": {
    number: "06", title: "Hermes — AI Social Media Manager", displayTitle: "Hermes", shortTitle: "Hermes / AI Social Media",
    kind: "ai-tool",
    type: "AI Social Media Manager / GPT / MCP",
    subtitle: "A GPT-powered social media assistant that researches Formula 1 news, creates posts for Facebook and Instagram, and waits for approval before publishing.",
    description: "Hermes AI Social Media Manager uses a GPT brain and MCP connections to Facebook and Instagram, checks F1 news every 30–60 minutes, researches and creates posts, then waits for human approval.",
    accent: "#d7ff43", accentSecondary: "#35431c",
    facts: [["AI brain", "GPT"], ["Connections", "MCP / Facebook & Instagram"], ["News checks", "Every 30–60 minutes"], ["Publishing", "Human approval required"]],
    overviewTitle: "From F1 news to a post ready for approval.",
    overviewBody: "Hermes handles the research and creation behind a Formula 1 social media presence. Its GPT brain works with MCP connections to access Facebook and Instagram accounts, checks for F1 news every 30–60 minutes and turns research into prepared posts. It presents the finished work and waits for the account owner's approval before publishing.",
    challengeTitle: "The challenge", challengeHeading: "The news keeps moving.",
    challengeBody: "Following Formula 1 means keeping up with a steady stream of news, researching the stories and turning them into social posts. That recurring work takes time, while the final editorial decision still needs a person.",
    solutionTitle: "The approach", solutionHeading: "Research, create, then ask.",
    solutionBody: "Hermes brings recurring news checks, GPT research and post creation into one workflow. MCP connects the assistant to Facebook and Instagram. The finished post is presented for review, with approval acting as the gate between preparation and publication.",
    features: [
      ["01", "Recurring F1 research", "Check for Formula 1 news every 30–60 minutes."],
      ["02", "GPT brain", "Research the stories and create posts from the findings."],
      ["03", "MCP connections", "Access connected Facebook and Instagram accounts."],
      ["04", "Approval before publishing", "Show the final work and wait for the account owner's decision."],
    ],
    stack: ["Hermes", "GPT", "MCP", "Facebook", "Instagram", "Human approval"],
    workflow: {
      title: "How the content flows.",
      intro: "MCP connects the accounts. Recurring F1 news checks feed the GPT brain, which researches and prepares posts for a human decision.",
      note: "Approval is the gate: Hermes shows the final work and waits for your decision before publishing. News checks repeat every 30–60 minutes.",
      summary: [["Input", "F1 news / every 30–60 min"], ["GPT brain", "Research & create"], ["Approval → output", "Facebook & Instagram"]],
      stages: [
        { label: "Input", title: "Connect & monitor", steps: [
          ["MCP account access", "Connect Hermes to the owner's Facebook and Instagram accounts through MCP."],
          ["Recurring news checks", "Check for Formula 1 news every 30–60 minutes."],
        ] },
        { label: "GPT brain", title: "Research & create", steps: [
          ["Research the story", "Use GPT to research the news and gather context for the post."],
          ["Prepare the final post", "Create the post and present the finished work for review."],
        ] },
        { label: "Approval & output", title: "Approve & publish", approval: true, steps: [
          ["Wait for approval", "Pause for the account owner's decision on the finished post."],
          ["Publish approved work", "Use the MCP-connected Facebook and Instagram accounts after approval."],
        ] },
      ],
    },
  },

  "cognitive-corporate-finance": {
    number: "07", title: "Cognitive Corporate Finance", shortTitle: "CognitiveCF",
    type: "Corporate website / Finance / Advisory",
    subtitle: "A corporate website for an international merchant advisory firm, presenting its technology-enhanced, Big Data-powered approach to capital raising and transaction support.",
    description: "Corporate website for Cognitive Corporate Finance, organizing its services, network, ecosystem, resources, funding proposition, team and contact pathways within a responsive international advisory platform.",
    image: "assets/projects/ccf.png", alt: "Cognitive Corporate Finance website preview",
    liveUrl: "https://www.cognitivecf.com", accent: "#9fb7c6", accentSecondary: "#293138",
    year: "2026", client: "Cognitive Corporate Finance", market: "International",
    role: "Digital presence", status: "Live",
    overviewTitle: "A corporate platform built around a differentiated proposition.",
    overviewBody: "The platform explains how Cognitive Corporate Finance combines merchant-advisory experience, technology and Big Data to support capital raising and transactions. A direct positioning statement leads into structured areas for services, network, ecosystem, resources, funding support, team and contact, helping companies and investors understand both the firm's capabilities and its differentiated international approach.",
    challengeTitle: "The challenge",
    challengeBody: "Corporate finance is complex and trust-sensitive. The proposition needed to feel credible while explaining what makes the firm's approach different from traditional advisory models.",
    solutionTitle: "The approach",
    solutionBody: "A concise positioning statement leads into structured corporate content. Monochrome visuals and straightforward navigation support clarity across the firm's ecosystem.",
    features: [
      ["01", "Distinct positioning", "The technology-enhanced approach leads the experience."],
      ["02", "Corporate clarity", "Services, network, resources and team follow a clear model."],
      ["03", "International tone", "Neutral visual language supports a cross-border audience."],
      ["04", "Responsive access", "Key content and contact pathways work across devices."],
    ],
    stack: ["WordPress", "CSS", "JavaScript", "Responsive UI", "Corporate content", "SEO", "Elementor"],
  },

  "ccf-apollo-email-tool": {
    number: "08", title: "Cognitive Corporate Finance Apollo Email Scraping Tool",
    displayTitle: "Apollo Email Scraping Tool", shortTitle: "CCF Apollo Email Tool",
    kind: "ai-tool",
    type: "AI tool / Cognitive Corporate Finance",
    subtitle: "A file-processing workflow that uploads an Excel list of names, surnames and optional website URLs, then generates a new Excel file containing matching email addresses.",
    description: "This tool lets the user upload an Excel file containing names, surnames and optionally website URLs, then processes the data to produce a new Excel file with the corresponding email addresses.",
    accent: "#8cd7ff", accentSecondary: "#173c50",
    facts: [["Project for", "Cognitive Corporate Finance"], ["Input", "Excel file with names, surnames and optional websites"], ["Output", "New Excel file with emails"], ["Format", "AI-assisted workflow"]],
    overviewTitle: "Turn a contact list into verified email addresses.",
    overviewBody: "The workflow begins with a spreadsheet upload. The user can provide first names, surnames and optionally website URLs, then the tool processes that data and generates a new Excel file containing the corresponding email addresses. The process is built to reduce manual research and make the output easier to review and use.",
    challengeTitle: "The challenge", challengeHeading: "Names alone are not enough to reach a contact.",
    challengeBody: "Sales and outreach teams often start with a spreadsheet of people and companies, but the actual email addresses are missing. The process needs to stay practical, quick and structured enough to handle multiple records without losing accuracy.",
    solutionTitle: "The approach", solutionHeading: "Upload a list, generate the emails, export the result.",
    solutionBody: "The user uploads an Excel file with names, surnames and optional website information. The system processes each record, identifies matching contact data and creates a new Excel document containing the resulting email addresses. This keeps the workflow simple: upload, process, review and export.",
    features: [
      ["01", "Excel upload", "The user uploads a spreadsheet containing names, surnames and optional website URLs."],
      ["02", "Email generation", "The workflow identifies matching email addresses for each record and compiles them into a new output file."],
      ["03", "Optional website input", "If available, website data helps improve matching and validation of the resulting contact details."],
      ["04", "Export-ready result", "The final Excel file is designed for easy review, reuse and follow-up outreach."],
    ],
    stack: ["Excel upload", "Name + surname matching", "Optional website enrichment", "Email generation", "Excel export"],
    workflow: {
      title: "How the workflow works.",
      intro: "The user starts with an Excel file of names and surnames, optionally including website URLs, and receives a new Excel file with matching email addresses.",
      note: "This is a practical contact-enrichment workflow designed for spreadsheet-based prospecting and outreach preparation.",
      summary: [["Input", "Excel file"], ["Process", "Match & generate emails"], ["Output", "New Excel with emails"]],
      stages: [
        { label: "Input", title: "Upload the spreadsheet", steps: [
          ["Name + surname", "Add the first and last names that need to be matched."],
          ["Optional website", "Include a website URL when available to improve email matching quality."],
        ] },
        { label: "Process", title: "Generate the results", steps: [
          ["Match records", "Review each person using the provided data and match against known contact information."],
          ["Create email list", "Prepare the corresponding email addresses for each row in the uploaded file."],
        ] },
        { label: "Output", title: "Export the Excel file", steps: [
          ["New spreadsheet", "Generate a new Excel document containing the email addresses."],
          ["Use for outreach", "Share the list for next-step communication and sales follow-up."],
        ] },
      ],
    },
  },
};
